/*
 * Copyright (c) 2020, Blair Butterworth
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.evilbird.engine.state;

import com.evilbird.engine.game.GameContext;

import java.util.List;

/**
 * Provides access to persist {@link State game states}, both those bundled
 * with the game and those generated by the user.
 *
 * @author Blair Butterworth
 */
public interface StateService
{
    GameContext context(StateIdentifier identifier);

    State get(StateIdentifier identifier);

    List<StateIdentifier> list(StateType type);

    void set(StateIdentifier identifier, State state);

    void remove(StateIdentifier identifier);
}
