/*
 * Blair Butterworth (c) 2019
 *
 * This work is licensed under the MIT License. To view a copy of this
 * license, visit
 *
 *      https://opensource.org/licenses/MIT
 */

package com.evilbird.warcraft.action.gather;

import com.evilbird.engine.events.EventQueue;
import com.evilbird.engine.item.Item;
import com.evilbird.engine.item.spatial.ItemNode;
import com.evilbird.warcraft.action.common.transfer.TransferEvent;
import com.evilbird.warcraft.action.common.transfer.TransferObserver;
import com.evilbird.warcraft.action.move.MoveEvent;
import com.evilbird.warcraft.action.move.MoveObserver;
import com.evilbird.warcraft.action.select.SelectEvent;
import com.evilbird.warcraft.action.select.SelectObserver;
import com.evilbird.warcraft.item.common.resource.ResourceContainer;
import com.evilbird.warcraft.item.common.resource.ResourceType;
import com.evilbird.warcraft.item.unit.gatherer.Gatherer;

import javax.inject.Inject;

/**
 * Instances of this class observe events generated by gathering actions and
 * report them to the {@link EventQueue}.
 *
 * @author Blair Butterworth
 */
public class GatherReporter implements GatherObserver, MoveObserver, SelectObserver, TransferObserver
{
    private EventQueue events;

    @Inject
    public GatherReporter(EventQueue events) {
        this.events = events;
    }

    @Override
    public void onObtainStarted(Gatherer gatherer, Item source, ResourceType type) {
        events.add(new GatherEvent(gatherer, GatherStatus.ObtainStarted, source, type));
    }

    @Override
    public void onObtainComplete(Gatherer gatherer, Item source, ResourceType type, float value) {
        events.add(new GatherEvent(gatherer, GatherStatus.ObtainComplete, source, type, value));
    }

    @Override
    public void onDepositStarted(Gatherer gatherer, Item destination, ResourceType type, float value) {
        events.add(new GatherEvent(gatherer, GatherStatus.DepositStarted, destination, type, value));
    }

    @Override
    public void onDepositComplete(Gatherer gatherer, Item destination, ResourceType type) {
        events.add(new GatherEvent(gatherer, GatherStatus.DepositComplete, destination, type));
    }

    @Override
    public void onGatherCancelled(Gatherer gatherer) {
        events.add(new GatherEvent(gatherer, GatherStatus.Cancelled));
    }

    @Override
    public void onMove(Item subject, ItemNode location) {
        events.add(new MoveEvent(subject, location));
    }

    @Override
    public void onSelect(Item item, boolean selected) {
        events.add(new SelectEvent(item, selected));
    }

    @Override
    public void onTransfer(ResourceContainer recipient, ResourceType resource, float oldValue, float newValue) {
        events.add(new TransferEvent(recipient, resource, oldValue, newValue));
    }
}
