/*
 * Copyright (c) 2020, Blair Butterworth
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.evilbird.engine.action.framework;

import com.badlogic.gdx.utils.Pool;
import com.evilbird.engine.action.Action;
import com.evilbird.engine.common.inject.PooledObject;
import com.evilbird.engine.common.lang.GenericIdentifier;
import com.evilbird.engine.common.lang.Identifier;
import com.evilbird.engine.device.UserInput;
import com.evilbird.engine.object.GameObject;
import com.evilbird.engine.object.GameObjectComposite;
import com.evilbird.engine.object.GameObjectReference;
import com.evilbird.engine.object.GameObjectReferencer;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Instances of this class represent a base class for {@link Action Actions},
 * containing common methods and properties utilised by many custom actions.
 *
 * @author Blair Butterworth
 */
public abstract class AbstractAction implements Action, GameObjectReferencer, PooledObject<Action>
{
    protected Identifier identifier;
    protected UserInput cause;

    protected GameObjectReference<GameObject> item;
    protected GameObjectReference<GameObject> target;

    protected transient Pool<Action> pool;

    public AbstractAction() {
    }

    /**
     * Resets the object for reuse. Object references should be set to
     * {@code null} and fields may be set to default values.
     */
    @Override
    public void reset() {
    }

    /**
     * Sets the state of the action so that it can be run again.
     */
    @Override
    public void restart() {
    }

    /**
     * Frees any resources held by the action. If the action is a
     * {@link PooledObject} then the action is returned to the pool.
     */
    @Override
    public void cancel() {
        Pool<Action> pool = getPool();
        if (pool != null) {
            pool.free(this);
        }
    }

    /**
     * Returns the {@link UserInput} event that generated the Action. Not all
     * Actions are generated by user interactions so this method should be
     * considered optional.
     *
     * @return a UserInput instance. May be {@code null}.
     */
    @Override
    public UserInput getCause() {
        return cause;
    }

    @Override
    public Identifier getIdentifier() {
        if (identifier == null) {
            return GenericIdentifier.Unknown;
        }
        return identifier;
    }

    @Override
    public Pool<Action> getPool() {
        return pool;
    }

    /**
     * Returns the {@link GameObject} that the Action will operate on.
     *
     * @return an {@code GameObject} instance. Will not return {@code null}.
     */
    @Override
    public GameObject getSubject() {
        return item != null ? item.get() : null;
    }

    public GameObjectReference<GameObject> getItemReference() {
        return item;
    }

    /**
     * Returns an optional target that the Action will manipulate.
     *
     * @return an {@code GameObject} instance. May return {@code null}.
     */
    @Override
    public GameObject getTarget() {
        return target != null ? target.get() : null;
    }

    public GameObjectReference<GameObject> getTargetReference() {
        return target;
    }

    /**
     * Sets the {@link UserInput} event that generated the Action.
     */
    @Override
    public void setCause(UserInput cause) {
        this.cause = cause;
    }

    /**
     * Set the actions unique identifier.
     */
    @Override
    public void setIdentifier(Identifier identifier) {
        this.identifier = identifier;
    }

    @Override
    public void setPool(Pool<Action> pool) {
        this.pool = pool;
    }

    @Override
    public void setSubject(GameObject gameObject) {
        this.item = gameObject != null ? new GameObjectReference<>(gameObject) : null;
    }

    public void setSubjectReference(GameObjectReference<GameObject> reference) {
        this.item = reference;
    }

    @Override
    public void setTarget(GameObject target) {
        this.target = target != null ? new GameObjectReference<>(target) : null;
    }

    public void setTargetReference(GameObjectReference<GameObject> reference) {
        this.target = reference;
    }

    @Override
    public void setContainer(GameObjectComposite root) {
        if (item != null) {
            item.setParent(root);
        }
        if (target != null) {
            target.setParent(root);
        }
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("identifier", identifier)
            .append("cause", cause)
            .append("subject", item)
            .append("target", target)
            .toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) { return false; }
        if (obj == this) { return true; }
        if (obj.getClass() != getClass()) { return false; }

        AbstractAction that = (AbstractAction)obj;
        return new EqualsBuilder()
            .append(identifier, that.identifier)
            .append(cause, that.cause)
            .append(item, that.item)
            .append(target, that.target)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
            .append(identifier)
            .append(cause)
            .append(item)
            .append(target)
            .toHashCode();
    }
}
