/*
 * Copyright (c) 2019, Blair Butterworth
 *
 * This work is licensed under the MIT License. To view a copy of this
 * license, visit
 *
 *        https://opensource.org/licenses/MIT
 */

package com.evilbird.warcraft.action.attack;

import com.evilbird.engine.action.Action;
import com.evilbird.engine.item.Item;
import com.evilbird.warcraft.action.common.scenario.ScenarioSetAction;
import com.evilbird.warcraft.item.unit.combatant.Combatant;

import javax.inject.Inject;

import static com.evilbird.engine.action.common.ActionRecipient.Target;
import static com.evilbird.engine.action.common.AnimateAction.animate;
import static com.evilbird.engine.action.common.AssignAction.assignIfAbsent;
import static com.evilbird.engine.action.common.DirectionAction.reorient;
import static com.evilbird.engine.action.common.RepeatedAudibleAction.playRepeat;
import static com.evilbird.engine.action.predicates.ActionPredicates.target;
import static com.evilbird.warcraft.action.attack.AttackAction.attack;
import static com.evilbird.warcraft.action.attack.AttackActions.AttackMelee;
import static com.evilbird.warcraft.action.attack.AttackEvents.attackComplete;
import static com.evilbird.warcraft.action.attack.AttackEvents.attackStarted;
import static com.evilbird.warcraft.action.attack.DeathAction.kill;
import static com.evilbird.warcraft.action.move.MoveToItemAction.move;
import static com.evilbird.warcraft.item.common.query.UnitPredicates.inRange;
import static com.evilbird.warcraft.item.common.query.UnitPredicates.isAlive;
import static com.evilbird.warcraft.item.common.query.UnitPredicates.notInRange;
import static com.evilbird.warcraft.item.unit.UnitAnimation.Idle;
import static com.evilbird.warcraft.item.unit.UnitAnimation.MeleeAttack;
import static com.evilbird.warcraft.item.unit.UnitAnimation.Move;
import static com.evilbird.warcraft.item.unit.UnitSound.Attack;

/**
 * Instances of this {@link Action} cause a given {@link Item} to attack
 * another, after first moving within attack range.
 *
 * @author Blair Butterworth
 */
public class AttackSequence extends ScenarioSetAction
{
    private transient AttackReporter reporter;

    /**
     * Constructs a new instance of this class given a {@link AttackReporter}
     * used to report events generated by the attack action. Notably attack
     * start, completion and cancellation.
     *
     * @param reporter  a {@code AttackReporter} instance. This parameter
     *                  cannot be {@code null}.
     */
    @Inject
    public AttackSequence(AttackReporter reporter) {
        this.reporter = reporter;
        feature(AttackMelee);
        reevaluate();
    }

    @Override
    protected void features() {
        Combatant combatant = (Combatant)getItem();
        reposition(combatant);
        engage(combatant);
    }

    private void reposition(Combatant combatant) {
        scenario("reposition")
            .whenTarget(isAlive())
            .whenTarget(notInRange(combatant))
            .givenItem(isAlive())
            .givenTarget(isAlive())
            .then(animate(Move))
            .then(move(reporter))
            .then(animate(Idle), reorient());
    }

    private void engage(Combatant combatant) {
        scenario("attack")
            .whenTarget(isAlive())
            .whenTarget(inRange(combatant))
            .givenItem(isAlive())
            .givenTarget(inRange(combatant))
            .then(animate(MeleeAttack))
            .then(attackStarted(reporter))
            .then(attack(), playRepeat(Attack, target(isAlive())))
            .then(attackComplete(reporter))
            .then(animate(Idle))
            .then(assignIfAbsent(kill(reporter), Target));
    }
}
