/*
 * Blair Butterworth (c) 2019
 *
 * This work is licensed under the MIT License. To view a copy of this
 * license, visit
 *
 *      https://opensource.org/licenses/MIT
 */

package com.evilbird.warcraft.action.placeholder;

import com.evilbird.engine.item.Item;
import com.evilbird.warcraft.action.common.create.CreateObserver;
import com.evilbird.warcraft.action.common.remove.RemoveObserver;

import javax.inject.Inject;

/**
 * Instances of this class observe events generated by placeholder actions.
 *
 * @author Blair Butterworth
 */
public class PlaceholderReporter implements CreateObserver, RemoveObserver
{
    @Inject
    public PlaceholderReporter() {
    }

    @Override
    public void onCreate(Item newItem) {
    }

    @Override
    public void onRemove(Item removed) {
    }
}
