/*
 * Blair Butterworth (c) 2019
 *
 * This work is licensed under the MIT License. To view a copy of this
 * license, visit
 *
 *      https://opensource.org/licenses/MIT
 */

package com.evilbird.warcraft.action.placeholder;

import com.evilbird.engine.events.EventQueue;
import com.evilbird.engine.item.Item;

import javax.inject.Inject;

/**
 * Instances of this class observe events generated by placeholder actions.
 *
 * @author Blair Butterworth
 */
public class PlaceholderReporter implements PlaceholderObserver
{
    private EventQueue events;

    @Inject
    public PlaceholderReporter(EventQueue events) {
        this.events = events;
    }

    @Override
    public void onPlaceholderAdded(Item builder, Item placeholder) {
        events.add(new PlaceholderEvent(builder, placeholder, PlaceholderStatus.Added));
    }

    @Override
    public void onPlaceholderRemoved(Item builder, Item placeholder) {
        events.add(new PlaceholderEvent(builder, placeholder, PlaceholderStatus.Removed));
    }
}
