/*
 * Copyright (c) 2020, Blair Butterworth
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.evilbird.warcraft.desktop;

import com.evilbird.engine.game.GameInjector;
import dagger.Component;

import javax.inject.Singleton;

/**
 * Provides access to the dependency injected services that facilitate the game
 * engine. Implementation of this class will be generated by Dagger, binding
 * interfaces specified in the {@link GameInjector} interface to concrete
 * implementations as declared in {@link WarcraftModule}.
 *
 * @author Blair Butterworth
 */
@Component(modules = {DesktopModule.class, WarcraftModule.class})
@Singleton
public interface DesktopInjector extends GameInjector
{
}
