/*
 * Copyright (c) 2019, Blair Butterworth
 *
 * This work is licensed under the MIT License. To view a copy of this
 * license, visit
 *
 *        https://opensource.org/licenses/MIT
 */

package com.evilbird.warcraft.desktop;

import com.evilbird.engine.game.GameInjector;
import dagger.Component;

import javax.inject.Singleton;

/**
 * Provides access to the dependency injected services that facilitate the game
 * engine. Implementation of this class will be generated by Dagger, binding
 * interfaces specified in the {@link GameInjector} interface to concrete
 * implementations as declared in {@link WarcraftModule}.
 *
 * @author Blair Butterworth
 */
@Component(modules = {DesktopModule.class, WarcraftModule.class})
@Singleton
public interface DesktopInjector extends GameInjector
{
}
